apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secret-sync-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "secret-sync-operator.name" . }}
    helm.sh/chart: {{ include "secret-sync-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "secret-sync-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "secret-sync-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "secret-sync-operator.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: GIT_REPO
          valueFrom:
            configMapKeyRef:
              name: {{ include "secret-sync-operator.fullname" . }}-config
              key: gitRepo
        - name: SOPS_FILE
          valueFrom:
            configMapKeyRef:
              name: {{ include "secret-sync-operator.fullname" . }}-config
              key: sopsFile
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
          