apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secret-sync-operator.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "secret-sync-operator.name" . }}
    helm.sh/chart: {{ include "secret-sync-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
