apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret-sync-operator.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "secret-sync-operator.name" . }}
    helm.sh/chart: {{ include "secret-sync-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  gitRepo: {{ .Values.gitRepo | b64enc }}
  sopsFile: {{ .Values.sopsFile | b64enc }}
  